"""Domain layer for XM QA chatbot."""

from .entities import BusinessStream, Project, ReportingPeriod, Submission
from .exceptions import (
    AmbiguousExtractionError,
    DashboardRenderError,
    DomainError,
    InvalidConfigurationError,
    InvalidProjectIdError,
    InvalidSubmissionTeamError,
    InvalidTimeWindowError,
    LLMExtractionError,
    MissingSubmissionDataError,
)
from .registries import (
    ReportingRegistry,
    StreamRegistry,
    build_default_registry,
    build_default_reporting_registry,
)
from .services import ValidationService
from .value_objects import (
    BucketCount,
    CapaStatus,
    DefectLeakage,
    ExtractionConfidence,
    PortfolioAggregates,
    PriorityBucket,
    PriorityMapping,
    ProjectId,
    QualityMetrics,
    RegressionTimeBlock,
    RegressionTimeEntry,
    TestCoverageMetrics,
    TimeWindow,
)

__all__ = [
    "AmbiguousExtractionError",
    "BucketCount",
    "BusinessStream",
    "CapaStatus",
    "DashboardRenderError",
    "DefectLeakage",
    "DomainError",
    "ExtractionConfidence",
    "InvalidConfigurationError",
    "InvalidProjectIdError",
    "InvalidSubmissionTeamError",
    "InvalidTimeWindowError",
    "LLMExtractionError",
    "MissingSubmissionDataError",
    "PortfolioAggregates",
    "PriorityBucket",
    "PriorityMapping",
    "Project",
    "ProjectId",
    "QualityMetrics",
    "RegressionTimeBlock",
    "RegressionTimeEntry",
    "ReportingPeriod",
    "ReportingRegistry",
    "StreamRegistry",
    "Submission",
    "TestCoverageMetrics",
    "TimeWindow",
    "ValidationService",
    "build_default_registry",
    "build_default_reporting_registry",
]
