"""Update submissions schema to match current model.

Revision ID: e238143a8d1a
Revises: edcda2791bed
Create Date: 2026-02-08 19:56:59.849808

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "e238143a8d1a"
down_revision: str | Sequence[str] | None = "edcda2791bed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("submissions", sa.Column("project_id", sa.String(), nullable=False))
    op.add_column("submissions", sa.Column("test_coverage", sa.JSON(), nullable=True))
    op.add_column("submissions", sa.Column("overall_test_cases", sa.JSON(), nullable=True))
    op.drop_index(op.f("ix_submissions_team_id"), table_name="submissions")
    op.drop_constraint(op.f("uq_team_month"), "submissions", type_="unique")
    op.create_index(op.f("ix_submissions_project_id"), "submissions", ["project_id"], unique=False)
    op.create_unique_constraint("uq_project_month", "submissions", ["project_id", "month"])
    op.drop_column("submissions", "project_status")
    op.drop_column("submissions", "team_id")
    op.drop_column("submissions", "qa_metrics")
    op.drop_column("submissions", "daily_update")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("submissions", sa.Column("daily_update", sqlite.JSON(), nullable=True))
    op.add_column("submissions", sa.Column("qa_metrics", sqlite.JSON(), nullable=True))
    op.add_column("submissions", sa.Column("team_id", sa.VARCHAR(), nullable=False))
    op.add_column("submissions", sa.Column("project_status", sqlite.JSON(), nullable=True))
    op.drop_constraint("uq_project_month", "submissions", type_="unique")
    op.drop_index(op.f("ix_submissions_project_id"), table_name="submissions")
    op.create_unique_constraint(op.f("uq_team_month"), "submissions", ["team_id", "month"])
    op.create_index(op.f("ix_submissions_team_id"), "submissions", ["team_id"], unique=False)
    op.drop_column("submissions", "overall_test_cases")
    op.drop_column("submissions", "test_coverage")
    op.drop_column("submissions", "project_id")
    # ### end Alembic commands ###
