"""Create submissions table.

Revision ID: edcda2791bed
Revises:
Create Date: 2026-02-03 20:53:49.754495

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "edcda2791bed"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "submissions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("month", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("qa_metrics", sa.JSON(), nullable=True),
        sa.Column("project_status", sa.JSON(), nullable=True),
        sa.Column("daily_update", sa.JSON(), nullable=True),
        sa.Column("raw_conversation", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "month", name="uq_team_month"),
    )
    op.create_index(op.f("ix_submissions_month"), "submissions", ["month"], unique=False)
    op.create_index(op.f("ix_submissions_team_id"), "submissions", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_submissions_team_id"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_month"), table_name="submissions")
    op.drop_table("submissions")
    # ### end Alembic commands ###
